name: Check
on: [push]
jobs:
  build:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Check for no untracked files
        run: |
          go install gitlab.com/jamietanna/tidied@latest
          tidied -verbose

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.60.1
          args: --timeout=3m

      - name: Build
        run: make build

      - name: Run `make check`
        run: make check
